# Generated by Django 5.1.2 on 2024-11-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('procesando', 'En proceso'), ('preparando', 'Recogiendo productos'), ('listo', 'Listo para retirar'), ('entregado', 'Entregado')], default='procesando', max_length=20),
        ),
    ]
