# Generated by Django 5.1.2 on 2024-12-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='creado',
        ),
    ]
